# Generated by Django 5.2.16 on 2026-07-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mon Restaurant', max_length=120, verbose_name='nom')),
                ('description_fr', models.TextField(blank=True, verbose_name='description (FR)')),
                ('description_en', models.TextField(blank=True, verbose_name='description (EN)')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('opening_hours_fr', models.TextField(blank=True, help_text='Une ligne par plage, ex : Lun–Ven : 11h–22h', verbose_name='horaires (FR)')),
                ('opening_hours_en', models.TextField(blank=True, verbose_name='horaires (EN)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant/', verbose_name='logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='restaurant/', verbose_name='image de couverture')),
            ],
            options={
                'verbose_name': 'restaurant',
            },
        ),
    ]
