# Generated by Django 5.2.16 on 2026-07-17 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='color_accent',
            field=models.CharField(default='#C2410C', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide. Format attendu : #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='couleur accent'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='color_accent_dark',
            field=models.CharField(default='#9A3412', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide. Format attendu : #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='couleur accent foncée'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='color_ink',
            field=models.CharField(default='#121212', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide. Format attendu : #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='couleur texte / encre'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='color_paper',
            field=models.CharField(default='#E8E6E1', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide. Format attendu : #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='couleur fond'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='color_surface',
            field=models.CharField(default='#F7F6F3', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide. Format attendu : #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='couleur surface'),
        ),
    ]
