# Generated by Django 5.2.16 on 2026-07-17 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurant_color_accent_restaurant_color_accent_dark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='téléphone')),
                ('subject', models.CharField(blank=True, max_length=160, verbose_name='sujet')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='envoyé le')),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='color_accent',
            field=models.CharField(default='#FF5A00', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide. Format attendu : #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='couleur accent'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='color_accent_dark',
            field=models.CharField(default='#E04E00', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide. Format attendu : #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='couleur accent foncée'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='color_ink',
            field=models.CharField(default='#0A0A0A', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide. Format attendu : #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='couleur texte / encre'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='color_paper',
            field=models.CharField(default='#F4F4F5', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide. Format attendu : #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='couleur fond'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='color_surface',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide. Format attendu : #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='couleur surface'),
        ),
    ]
