# Generated by Django 5.2.16 on 2026-07-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text="Utilisée si aucune image de couverture n'est uploadée.", verbose_name='URL de couverture'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo_url',
            field=models.URLField(blank=True, help_text="Utilisée si aucun fichier logo n'est uploadé.", verbose_name='URL du logo'),
        ),
    ]
