# Generated by Django 5.2.16 on 2026-07-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('phone', models.CharField(max_length=30, verbose_name='téléphone')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='heure')),
                ('guests', models.PositiveIntegerField(default=2, verbose_name='nombre de personnes')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'réservation',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
