# Generated by Django 5.2.16 on 2026-07-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Manager'), ('caissier', 'Caissier'), ('serveur', 'Serveur'), ('cuisine', 'Cuisine')], default='serveur', max_length=20, verbose_name='rôle'),
        ),
    ]
