# Generated by Django 5.2.16 on 2026-07-17 15:15

import tables.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='numéro')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='capacité')),
                ('qr_token', models.CharField(default=tables.models._new_token, editable=False, max_length=64, unique=True, verbose_name='token QR')),
                ('status', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupée')], default='libre', max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'table',
                'ordering': ['number'],
            },
        ),
    ]
