# Generated by Django 5.2.16 on 2026-07-17 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], max_length=3, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant')),
                ('reason', models.CharField(max_length=255, verbose_name='motif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entry', to='orders.order', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'mouvement de caisse',
                'verbose_name_plural': 'mouvements de caisse',
                'ordering': ['-created_at'],
            },
        ),
    ]
