# Generated by Django 5.2.16 on 2026-07-18 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(verbose_name='début de période')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='clôturée le')),
                ('total_in', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total entrées')),
                ('total_out', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total sorties')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant attendu')),
                ('counted_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant compté')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='écart')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_closures', to=settings.AUTH_USER_MODEL, verbose_name='clôturée par')),
            ],
            options={
                'verbose_name': 'clôture de caisse',
                'verbose_name_plural': 'clôtures de caisse',
                'ordering': ['-closed_at'],
            },
        ),
    ]
