# Generated by Django 5.2.16 on 2026-07-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=120, verbose_name='nom (FR)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='nom (EN)')),
                ('position', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['position', 'name_fr'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=120, verbose_name='nom (FR)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='nom (EN)')),
                ('description_fr', models.TextField(blank=True, verbose_name='description (FR)')),
                ('description_en', models.TextField(blank=True, verbose_name='description (EN)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='image')),
                ('is_active', models.BooleanField(default=True, verbose_name='disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'plat',
                'verbose_name_plural': 'plats',
                'ordering': ['category__position', 'name_fr'],
            },
        ),
    ]
