# Generated by Django 5.2.16 on 2026-07-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_url',
            field=models.URLField(blank=True, help_text="Utilisée si aucun fichier image n'est uploadé.", verbose_name='URL image'),
        ),
    ]
