# Generated by Django 5.2.16 on 2026-07-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('servie', 'Servie'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='statut')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='payée le')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tables.table', verbose_name='table')),
            ],
            options={
                'verbose_name': 'commande',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix unitaire')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.dish', verbose_name='plat')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'ligne de commande',
            },
        ),
    ]
