# Generated by Django 5.2.16 on 2026-07-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('prete', 'Prête'), ('servie', 'Servie'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='statut'),
        ),
    ]
