# Generated by Django 5.2.16 on 2026-07-18 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='remise'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_approvals', to=settings.AUTH_USER_MODEL, verbose_name='remise validée par'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='motif de remise'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_requests', to=settings.AUTH_USER_MODEL, verbose_name='remise demandée par'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_status',
            field=models.CharField(choices=[('none', 'Aucune'), ('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='none', max_length=20, verbose_name='statut remise'),
        ),
    ]
