# Generated by Django 5.2.16 on 2026-08-30 09:49

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_customer_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_token',
            field=models.CharField(default=orders.models._new_invoice_token, editable=False, max_length=64, unique=True, verbose_name='token facture'),
        ),
    ]
