# Generated by Django 5.2.16 on 2026-09-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_invoice_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('especes', 'Espèces'), ('mobile', 'Mobile Money'), ('orange', 'Orange Money'), ('airtel', 'Airtel Money')], default='especes', max_length=20, verbose_name='méthode de paiement'),
        ),
    ]
